modLoader="kotlinforforge"
loaderVersion="${kotlin_for_forge_loader_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kotlinforforge"
type="required"
versionRange="${kotlin_for_forge_loader_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="immersive_portals_core"
type="optional"
versionRange="[${immersive_portals_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sable"
type="optional"
versionRange="[${sable_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="distanthorizons"
type="optional"
versionRange="[2.2.1,)"
ordering="AFTER"
side="CLIENT"
